- platform: mqtt
  name: "Temperature"
  state_topic: "office/sensor1"
  unit_of_measurement: '°C'
  value_template: "{{ value_json.temperature }}"

- platform: mqtt
  name: "Humidity"
  state_topic: "office/sensor1"
  unit_of_measurement: '%'
  value_template: "{{ value_json.humidity }}"

- platform: mqtt
  name: "illuminance"
  state_topic: "office/sensor1"
  unit_of_measurement: 'lx/lm'
  value_template: "{{ value_json.humidity }}"